/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_content_delivery_bucket": "angularjspython-20200429165211-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "ap-southeast-1",
    "aws_content_delivery_url": "https://d1kv3704ep5gh7.cloudfront.net",
    "aws_cognito_identity_pool_id": "ap-southeast-1:93e88c64-fb42-436e-8a97-fd7cd148c31a",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_rjwFgbjbv",
    "aws_user_pools_web_client_id": "5r1c203u5vbia258tf0gsvl8k8",
    "oauth": {
        "domain": "angularjspython4af538ef-4af538ef-prod.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "seller",
            "endpoint": "https://cmsdj8wpsh.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "dev-candidate-service",
            'endpoint': 'https://o08r0c50fj.execute-api.ap-south-1.amazonaws.com/dev',
            "region": "ap-south-1"
        }
    ],
    "social": {
        "FB": "325736885061077"
    }
};


export default awsmobile;
